-- One source table DBT.DEV_YANCHUN_PUBLIC.collection_payment
---Another source table DBT.DEV_YANCHUN_PUBLIC.collection_weekly

WITH COLLECTIONS AS
(
    SELECT * FROM DBT.DEV_YANCHUN_PUBLIC.collection_payment
    WHERE WEEK_START_DS >= DATE('2022-10-03')
        AND DAYS_SINCE_PAYBACK_DATE < 7

),
USERS AS (
  SELECT
         COALESCE(CAST(advance_id AS varchar), overdraft_id) AS overdraft_id,
         is_new_user
  FROM analytic_db.dbt_marts.dim_advance_users
),
REPAYMENT_RATE AS
(
    SELECT
        C.WEEK_START_DS,
        C.DAYS_SINCE_PAYBACK_DATE,
        USERS.IS_NEW_USER,
        SUM(OUTSTANDING_BALANCE) AS OUTSTANDING_BALANCE,
        SUM(AMOUNT_DUE) AS TOTAL_AMOUNT_DUE
    FROM COLLECTIONS C
    JOIN USERS
        ON C.OVERDRAFT_ID = USERS.OVERDRAFT_ID
    GROUP BY 1, 2
),
AGG AS
(
    SELECT
        WEEK_START_DS,
        IS_NEW_USER,
        MAX(TOTAL_AMOUNT_DUE) AS TOTAL_AMOUNT_DUE
    FROM REPAYMENT_RATE
),
REPAYMENT_RATE_REFINE AS
(
    SELECT R.*
    FROM REPAYMENT_RATE R INNER JOIN AGG
        ON R.WEEK_START_DS = AGG.WEEK_START_DS
        AND R.IS_NEW_USER = AGG.IS_NEW_USER
    WHERE R.TOTAL_AMOUNT_DUE = AGG.TOTAL_AMOUNT_DUE
)
SELECT * FROM REPAYMENT_RATE_REFINE