DROP table IF EXISTS DBT.DEV_YANCHUN_PUBLIC.multi_draw_consecutive;
CREATE TABLE  DBT.DEV_YANCHUN_PUBLIC.multi_draw_consecutive AS
WITH DAVE_ADVANCE AS
(
    SELECT *
    FROM DBT.DEV_YANCHUN_PUBLIC.multi_draw_raw
    WHERE FUNDING_NAME = 'ADVANCE_DAVE'
)
SELECT
    USER_ID,
    FUNDING_DATE,
    DATEDIFF('DAY',
    LAG(FUNDING_DATE, 1) OVER (PARTITION BY USER_ID ORDER BY FUNDING_DATE ASC),
    FUNDING_DATE) AS CONSECUTIVE_DIFF
FROM DAVE_ADVANCE

