DROP table IF EXISTS DBT.DEV_YANCHUN_PUBLIC.multi_draw_right_after;
CREATE TABLE  DBT.DEV_YANCHUN_PUBLIC.multi_draw_right_after AS
WITH DAVE_ADVANCE AS
(
    SELECT
        USER_ID,
        FUNDING_DATE,
        ORDERNUMBER,
        R_AMOUNT,
        T_AMOUNT
    FROM DBT.DEV_YANCHUN_PUBLIC.multi_draw_raw
    WHERE FUNDING_NAME = 'ADVANCE_DAVE'
),
COMPETITORS AS
(
    SELECT
        USER_ID,
        FUNDING_DATE AS COMPETITOR_FUNDING_DATE,
        ORDERNUMBER,
        T_AMOUNT AS COMPETITOR_AMOUNT
    FROM DBT.DEV_YANCHUN_PUBLIC.multi_draw_raw
    WHERE FUNDING_NAME <> 'ADVANCE_DAVE'
        AND ORDERNUMBER > 0
)
SELECT
    COMPETITORS.USER_ID AS USER_ID,
    COMPETITORS.COMPETITOR_FUNDING_DATE,
    DAVE_ADVANCE.FUNDING_DATE,
    COMPETITORS.ORDERNUMBER,
    COMPETITORS.COMPETITOR_AMOUNT,
    DAVE_ADVANCE.R_AMOUNT,
    DAVE_ADVANCE.T_AMOUNT,
    DATEDIFF('DAY', DAVE_ADVANCE.FUNDING_DATE, COMPETITORS.COMPETITOR_FUNDING_DATE) AS RIGHTAFTER
FROM COMPETITORS
LEFT JOIN DAVE_ADVANCE
ON COMPETITORS.USER_ID = DAVE_ADVANCE.USER_ID
AND COMPETITORS.ORDERNUMBER = DAVE_ADVANCE.ORDERNUMBER